server:
  port: 1607
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #database-platform: org.hibernate.dialect.MySQL5Dialect
        
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
       
      base-path: /myactuator
      
  info:
    git:
      enabled: true
    env:
      enabled: true
logging:
  level:
    com:
    zensar: 
    springbootdemo: error   
    
  endpoint:
    shutdown:
      enabled: true
      
info:
 createdby: vishnuvardhan
 modified: 22/06/2022
 


   